### DISCUSSION TITLE
Runnign NPMPlus but not getting redirected

### DISCUSSION THREAD

**Discussion by DJKatastrof** [steveiliop56/tinyauth#167] [Q&A]
Hey!
This application seems promising since I want to get away from Authelia to Pocket-ID.
Same as this https://github.com/steveiliop56/tinyauth/discussions/112 , im not getting redirected to my application.

Any ideas? 

Address bar after login
https://tiny.domain.com/login?redirect_uri=https://ldap.domain.com/login 

NPMPlus Advanced code since your NPM code didn't work on NPMPlus

```
# Simple forward auth setup
location / {
    auth_request /auth;
    proxy_pass http://192.168.1.18:1717;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location = /auth {
    internal;
    proxy_pass http://192.168.1.50:3000/api/auth/nginx;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Original-URI $request_uri;
}

location = /login {
    return 302 https://tiny.domain.com/login?redirect_uri=$scheme://$http_host$request_uri;
}
```

Docker config and some errors

2025-05-27T07:36:37Z ERR Failed to get session error="securecookie: the value is not valid"
2025-05-27T07:36:37Z ERR Failed to get session error="securecookie: the value is not valid"
2025-05-27T07:36:37Z ERR Failed to get session cookie error="securecookie: the value is not valid

```
services:
    tinyauth:
      image: ghcr.io/steveiliop56/tinyauth:v3
      container_name: tinyauth
      restart: unless-stopped

      ports:
        - "3000:3000"
      environment:
        - SECRET=redacted
        - APP_URL=https://tiny.domain.com
        - USERS=redacted
        - GENERIC_CLIENT_ID=redacted
        - GENERIC_CLIENT_SECRET=redcated
        - GENERIC_AUTH_URL=https://id.domain.com/authorize
        - GENERIC_TOKEN_URL=https://id.domain.com/api/oidc/token
        - GENERIC_USER_URL=https://id.domain.com/api/oidc/userinfo
        - GENERIC_SCOPES=openid email profile groups
        - GENERIC_NAME=Pocket ID
        #- OAUTH_AUTO_REDIRECT=generic
        - COOKIE_SECURE=true

```
