### DISCUSSION TITLE
UX when logged out

### DISCUSSION THREAD

**Discussion by shelldandy** [steveiliop56/tinyauth#37] [Q&A] [answered]
I was wondering if you had any suggestions on how to improve this UX (it may be something on my end misconfigured)

say for instance i protected whoami with tinyauth on traefik with authentik

my flow from logged out user would be:

```
- enters whoami domain
- gets transferred to tinyauth domain
- click generic oauth
- gets transferred to authentik to login
- gets tranferred to tinyauth logged in screen
- user then has to manually type in whoami domain again to finally access it
```

Is there a way we can go from logged out to logged in and in the same domain initially trying to get accessed?

**Comment by steveiliop56** [comment]
That's actually what's supposed to happen. When you login can you check if any cookies are set? It should set a `tinyauth_redirect_uri`

**Reply by shelldandy** [reply]
@steveiliop56 i can see the cookie being set to the `tinyauth` url not to the `whoami` url

**Reply by steveiliop56** [reply]
When you go to `whoami.example.com` and the login screen appears what's the `redirect_uri` in the URL? E.g. 
<img width="333" alt="image" src="https://github.com/user-attachments/assets/906f1a8f-8310-414e-8806-5aae44914302" />

**Reply by shelldandy** [reply]
its the tinyauth url: `https://tinyauth.domain/login?redirect_uri=https://tinyauth.domain`

**Reply by steveiliop56** [reply]
What's your docker compose file?

**Reply by shelldandy** [reply]
The relevant bits are these: 

```yml
  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:latest
    environment:
      - SECRET=${TINYAUTH_SECRET}
      - APP_URL=https://${TINYAUTH_URL}
      - USERS=${TINYAUTH_USERS}
      - GENERIC_CLIENT_ID=${GENERIC_CLIENT_ID}
      - GENERIC_CLIENT_SECRET=${GENERIC_CLIENT_SECRET}
      - GENERIC_AUTH_URL=${GENERIC_AUTH_URL}
      - GENERIC_TOKEN_URL=${GENERIC_TOKEN_URL}
      - GENERIC_SCOPES=${GENERIC_SCOPES}
      - GENERIC_USER_URL=${GENERIC_USER_URL}
    labels:
      traefik.enable: true
      traefik.http.routers.tinyauth.rule: Host(`${TINYAUTH_URL}`)
      traefik.http.services.tinyauth.loadbalancer.server.port: 3000
      traefik.http.middlewares.tinyauth.forwardauth.address: https://${TINYAUTH_URL}/api/auth/traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
      - authentik_network
  
  whoami:
    container_name: whoami
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.middlewares=tinyauth"
    networks:
      - frontend
    restart: unless-stopped
```
