### ISSUE TITLE
[FEATURE] Add coolify integration to the docs

### ISSUE THREAD

**Issue by waseemw** [steveiliop56/tinyauth#107]
I got it working on coolify using this config, and wanted to share it so that it can be added to the docs:

1. create 'empty docker compose' service (here user/pass is admin:admin) and secret is just random:

```yaml
services:
  tinyauth:
    image: 'ghcr.io/steveiliop56/tinyauth:v3'
    container_name: tinyauth
    restart: unless-stopped
    environment:
      - SECRET=tOPwhbiMF4hbipPK4hpPK4hbipPK4hbb
      - 'APP_URL=https://auth.yourdomain.com'
      - 'USERS=admin:$$2a$$12$$CtdKwh6uzF1VkmdTDZje3eRilGu9Nj1kjiirevBvM3M6mAwzb43SW'
```
and for the service in coolify ui set the domain to `https://auth.yourdomain.com:3000` so it points to 3000 in the container

2. add dynamic configuration in proxy settings (don't change the address here, it should point to docker instance not public hostname)

```yaml
http:
  middlewares:
    tinyauth:
      forwardAuth:
        address: 'http://tinyauth:3000/api/auth/traefik'
        trustForwardHeader: true
```

3. then for every service, to protect it simply add to the labels:
```
- traefik.http.middlewares.tinyauth@file
```

Example webpage protected by tinyauth in coolify:

```yaml
version: '3.8'
services:
  webserver:
    image: 'nginx:alpine'
    container_name: simple_default_webpage
    restart: unless-stopped
    labels:
      - traefik.http.middlewares.tinyauth@file
```
