### ISSUE TITLE
[BUG] Pocket-ID not working?

### ISSUE THREAD

**Issue by viriatusX** [steveiliop56/tinyauth#136]
<img width="667" alt="Image" src="https://github.com/user-attachments/assets/4d1bf516-f5bd-49cf-9890-09e571a60e40" />

I don't know if it's a Bug or something has changed in TinyAuth.
I have Pocket-ID configured to use Passkeys but in the TinyAuth part I get an error.

<img width="1003" alt="Image" src="https://github.com/user-attachments/assets/cc5061ca-d723-4d95-8851-9f767089c3af" />

<img width="508" alt="Image" src="https://github.com/user-attachments/assets/290548d0-f192-48aa-ba7f-f4864837d9d6" />

I have seen that the mate @nebula-it has it working. That is why I say that I do not know if it is a Bug or something has changed or I have misconfigured.

Thanks for your work.

**Comment by steveiliop56** [comment]
Hello!

Seems like tinyauth is getting an empty email address. Are you trying to login with the admin account or a simple account from pocket ID?

**Comment by viriatusX** [comment]
I have tried with admin account and with another account created in Pocket ID and same error.

**Comment by steveiliop56** [comment]
I will try to make an alpha/nightly release that will include more logs on what's getting parsed and what not, then we will be able to debug further.

**Comment by viriatusX** [comment]
Great. I will wait for this alpha release to debug the real problem

**Comment by nebula-it** [comment]
Hey @viriatusX 
Does your account has email set in pocket-id?
The combo is working for me, both on latest versions.

**Comment by viriatusX** [comment]
> Hey [@viriatusX](https://github.com/viriatusX) Does your account has email set in pocket-id? The combo is working for me, both on latest versions.

Yes of coure.

In pocket-id I have specified the email in my account. Within the OIDC Clients tab configuration I have specified the TinyAuth Callback URL (https://auth.mydomain.com/api/oauth/callback/generic

Logout Callback URL is empty.

And in group of assigned users I have selected which includes the user.

There is no other configuration, it's correct?

As a reverse proxy I use Pangolin (Traefik). I don't know if I have to add anything special.

**Comment by nebula-it** [comment]
This is what I have in my config:
```
  COOKIE_SECURE: "true"
  DISABLE_CONTINUE: "true"
  SECRET: 
  APP_URL: https://<tiny auth url>
  GENERIC_CLIENT_ID: client id from pocket-id
  GENERIC_CLIENT_SECRET: secret from pocket-id
  GENERIC_AUTH_URL: https://pocketid.example.com/authorize
  GENERIC_TOKEN_URL: https://pocketid.example.com/api/oidc/token
  GENERIC_USER_URL: https://pocketid.example.com/api/oidc/userinfo
  GENERIC_SCOPES: "openid email profile"
  GENERIC_NAME: PocketID
```

Try a curl from tiny auth container to your pocker id url and see if it works and vice-versa. This is just to ensure DNS is good and they can each each other
