### ISSUE TITLE
[BUG] Internal server error OAUTH after server restart

### ISSUE THREAD

**Issue by mistrello96** [steveiliop56/tinyauth#148]
**Describe the bug**

After the system is restarted, the OAUTH login produces Interal Server Error.
The container of tinyauth restart as expected, and the login works using username and password.
If I try to use the Google OAUTH instead of user and password, I get an Internal Server Error. 
The problem disappears (OAUTH works again) if I manually restart the tinyauth container.

```
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3
    container_name: tinyauth
    restart: unless-stopped
    environment:
      - SECRET=loreipsum
      - APP_URL=loreipsum
      - USERS=loreipsum:loreipsum
      - GOOGLE_CLIENT_ID=loreipsum
      - GOOGLE_CLIENT_SECRET=loreipsum
      - OAUTH_WHITELIST=loreipsum
    networks:
      - web
    depends_on:
      traefik:
        condition: service_started
        restart: true
```

**To Reproduce**
1. Start both traefik and tinyauth services (with google OAUTH enabled) with a restart policy
2. Restart the system
3. Try to login using the OAUTH method

**Expected behavior**
The  login should work for both user/password and OAUTH

**Screenshots**
![Image](https://github.com/user-attachments/assets/c71aeaf8-51b2-40dd-b2af-4857534213c4)

**Logs**
No significant log is produced from the container

**Device (please complete the following information):**
 - OS: Debian 12
 - Chrome
 - Tinyauth V3
 - Docker 28.0.4
