### ISSUE TITLE
Bypass local IP's (or single IP)?

### ISSUE THREAD

**Issue by schumi2004** [steveiliop56/tinyauth#160]
Would it be possible to bypass Tinyauth to bypass authentication for local IP's or a single IP?

I couldn't find an existing issue for it only found something for API's

**Comment by steveiliop56** [comment]
Hello!

Currently this is not possible but it's a good idea for a future release. Will add it to my to-do list!

**Comment by ilkersigirci** [comment]
This would be awesome feature. Moreover, bypassing `TOTP` feature for specific IPs would be beneficial for local development and testing without sacrificing the security for public services. Is there any roadmap for these features? Thanks in advance

**Comment by steveiliop56** [comment]
I am planning to add a `tinyauth.ip.allow`  label that will basically disable all authentication for a specific IP whether it is using TOTP/OAuth etc. This can be followed by a `tinyauth.ip.block` to have a blocklist of IP addresses. There is a [project](https://github.com/users/steveiliop56/projects/2) available so you can check what I am working on, what I am planning to work on and the priorities (right now I am not working on something due to school exams). There is also an available [milestone](https://github.com/steveiliop56/tinyauth/milestone/3) of the features/fixes/improvements I plan to include in the next release.

**Comment by steveiliop56** [comment]
Added in #211. You will be able to do `tinyauth.ip.allow: 10.10.10.0/24,192.168.1.5` to allow the comma separated IP addresses or all the addresses included in the CIDRs. You will also be able to do `tinyauth.ip.block` to block IP addresses or all the addresses included in the CIDRs the same way as with the allow.

**Comment by ilkersigirci** [comment]
@steveiliop56  I have tried the latest `3.5.0` release. Adding `tinyauth.ip.allow` label to tinyauth services doesn't seem to have any effect. The login page still appears on the allowed IPs. Is there anything more to configure?

**Comment by steveiliop56** [comment]
@ilkersigirci a lot of things could be misconfigured resulting in this issue. Firstly try checking your logs and see if Tinyauth sees the correct IP address in the requests (if it sees something like `172.x.x.x` it means it's an internal one and something is wrong with networking). If it sees your IP addresses try adding the `tinyauth.domain` label in your app with the domain of the app, for example if you have exposed your app to `myapp.example.com` try to use the `tinyauth.domain: myapp.example.com` label in order for Tinyauth to identify the container. If nothing works then please provide the debugs logs of Tinyauth so we can get some insights on what's happening.

**Comment by ilkersigirci** [comment]
Tinyauth logs are the following. `192.168.90.254` is the static IP address of my `traefik` reverse proxy. which  define like;

```yml
    networks:
      my_network:
        ipv4_address: 192.168.90.254
``` 

<img width="971" height="231" alt="Image" src="https://github.com/user-attachments/assets/1c65aa0c-9d94-4ca3-bb76-f20dd85ab3fa" />

Should I add the label to `tinyauth` container, right? I have tried to add both `traefik` container and `tinyauth`. But still doesn't change anything

**Comment by steveiliop56** [comment]
Ohh I misunderstood your original comment. The Tinyauth login screen will be shown regardless of the the labels. You are supposed to use the labels in a per-app basis. This way someone can still login but if their IP is not allowed Tinyauth will not allow them to access the resource. This is my fault for not explaining it correctly but documentation will come in the following days explaining everything in depth.

**Comment by ilkersigirci** [comment]
Oh, I get it now. I thought that this feature allow me to competely bypass tinyauth authentication on the given IP range. Would you consider implementing this feature in the near future? I was using this feature in the `Authelia` to allow my LAN devices to bypass the auth. I think this feature would be great for your awesome app. Thanks in advance

**Comment by steveiliop56** [comment]
Oh man I implemented the wrong thing. You are absolutely correct I don't know what went wrong with my thought process when implementing this. In the next release I will add `tinyauth.ip.bypass` to completely get rid of Tinyauth login screen and everything for specific apps. I am sorry for the inconvenience, I will try to release this as soon as possible. I am reopening this issue.

**Comment by ilkersigirci** [comment]
> Oh man I implemented the wrong thing. You are absolutely correct I don't know what went wrong with my thought process when implementing this. In the next release I will add `tinyauth.ip.bypass` to completely get rid of Tinyauth login screen and everything for specific apps. I am sorry for the inconvenience, I will try to release this as soon as possible. I am reopening this issue.

No worries, thank you for the quick response. I will look forward to see this. One question, though. Could you make the bypass as global like an environment variable for the tinyauth container instead of per app basis config? For example, I want all my containers to bypass tinyauth in the local IPs. Instead of adding tinyauth label to all of them, giving this IP ranges to tinyauth container would really simplify the process

**Comment by steveiliop56** [comment]
I have the implementation ready but I prefer going with a per-app basis config to increase security. With global configs a lot of things can go wrong and create security holes. It will be a bit of an inconvenience but I think it's the best approach going forward.

**Comment by ilkersigirci** [comment]
> I have the implementation ready but I prefer going with a per-app basis config to increase security. With global configs a lot of things can go wrong and create security holes. It will be a bit of an inconvenience but I think it's the best approach going forward.

Okay, fair enough

**Comment by steveiliop56** [comment]
Added *correctly* this time in https://github.com/steveiliop56/tinyauth/commit/0ace88a8774b8df7499f7fb6d2661b6a738d9a1c. You will be able to do `tinyauth.ip.bypass` and provide comma separated list of CIDRs or IPs that will be immediately allowed access to the resource without needing any sort of authentication. Tinyauth will also forward any headers you have set or the basic authentication.

**Comment by ilkersigirci** [comment]
@steveiliop56  Thanks for the quick fix. Could you provide simple usage example,please? Even though I am using the `3.6.0` version, I can't still make it bypass my services

**Comment by steveiliop56** [comment]
You will have to use the `tinyauth.ip.bypass` label.

**Comment by ilkersigirci** [comment]
I am already using `tinyauth.ip.bypass` label like the following. I must be misconfigured something but I couldn't find out what I am doing wrong atm. Hence, I kindly ask the working example for this

```yml
...
labels:
      tinyauth.ip.bypass: "127.0.0.1/32,10.8.0.0/24,192.168.0.0/16,172.16.0.0/12"
```

**Comment by steveiliop56** [comment]
And tinyauth still prompts you to login? Most likely the labels aren't recognized. Try to also add the `tinyauth.domain` label with the app's domain as value (not tinyauth's domain).

**Comment by ilkersigirci** [comment]
Unfortunately,yes. Btw, I am not seeing any `bypass` log in the tinyauth container. My current config is the following. I have added `tinyauth.domain` as you said but it didn't fix the bypass part.

```yml
services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    restart: $BASE_RESTART_POLICY
    profiles:
      - core
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONFIGDIR/glance/config:/app/config
      - $CONFIGDIR/glance/assets:/app/assets
    environment:
      TZ: $TZ
      MY_SECRET_TOKEN: "glance_secret_token"
      DOMAINNAME: $DOMAINNAME
    labels:
      tinyauth.domain: "glance.$DOMAINNAME"
      tinyauth.ip.bypass: "127.0.0.1/32,10.8.0.0/24,192.168.0.0/16,172.16.0.0/12"
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.glance-rtr.entrypoints: "websecure"
      traefik.http.routers.glance-rtr.rule: "Host(`glance.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.glance-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.glance-rtr.service: "glance-svc"
      traefik.http.services.glance-svc.loadbalancer.server.port: "8080"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "glance"
      homepage.icon: "glance.png"
      homepage.href: "https://glance.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "A self-hosted dashboard that puts all your feeds in one place"
```
