### ISSUE TITLE
[BUG] Certificate signed by unknown authority.

### ISSUE THREAD

**Issue by gnr8shn** [steveiliop56/tinyauth#174]
**Describe the bug**
Using Caddydockerproxy, Tinyauth, Pocket-ID and Whoami. All internal with private certificates signed by step-ca from [Smallstep](https://github.com/smallstep/certificates). 
After successful OAuth login by Pocket-ID, Tinyauth fails to communicate with Pocket-ID citing **certificate signed by unknown authority**.

**To Reproduce**
1. Go to whoami.lala.lan/. Tinyauth prompt appears, with email and Pocket ID options
2. Click on Pocket ID. The Pocket ID prompt appears **Do you want to sign in to Tinyauth with your Pocket ID account?**.
3. Click on sign in.
4. Enter your passkey.
5. The following popup appears. 
	```
	Internal Server Error
	An error occurred on the server and it currently cannot serve your request.
	Try Again
	```
**Logs**
`2025-05-29T07:30:42Z ERR Failed to exchange token error="Post \"https://pocket-id.lala.lan/api/oidc/token\": tls: failed to verify certificate: x509: certificate signed by unknown authority"`

**Expected behavior**
Tinyauth should accept the privately signed certificate and forward to the whoami website.

**Screenshots**

**Device (please complete the following information):**

- OS: Android 15. Lineage 22.2-20250509. Pixel 7
- Browser: Firefox 138.0.4, normal and Private tabs. Firefox Focus 138.0.4. Duckduckgo 5.234.2. Chrome 136.0.7103.12, normal and icognito tabs.
- Tinyauth v3.3.1 created
- Docker version 28.1.1, build 4eba377
- Pocket-ID version v0.53.0

**Additional context**
It would be nice to add the root certificates of private CAs

**docker-compose.yaml**
```
services:
  caddysecurity:
    container_name: caddysecurity
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - COOKIE_SECURE=true
      - CADDY_INGRESS_NETWORKS=caddysecurity
    networks:
      - caddysecurity
    labels:
      caddy.acme_ca: https://step-ca.lan:4443/acme/acme/directory
      caddy.acme_ca_root: /config/Smallstep_Root_CA.cer
      caddy: (tinyauth_forwarder)
      caddy.forward_auth: auth:3000
      caddy.forward_auth.uri: /api/auth/caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/caddy_data:/data
      - $PWD/caddy_config:/config
    restart: unless-stopped

  auth:
    container_name: auth
    hostname: auth
    image: ghcr.io/steveiliop56/tinyauth:v3
    networks:
      - caddysecurity
    restart: unless-stopped
    environment:
      - COOKIE_SECURE=true
      - APP_URL=https://auth.lala.lan
      - SECRET=secret-has-to-be-32-charsxxxxxxx
      - USERS=${USERNAME}:$$2a$$10$$LiRbFBqNiMc.tj7cuBY6LOy1epICyQgpRS9UIu5g.d2BKOiLHk0dG      # ${USERNAME}
      - GENERIC_CLIENT_ID=1674e1e7-cde9-429b-b8e3-b75b509b1a8f
      - GENERIC_CLIENT_SECRET=6nOPO3HCcyVqkwEoStWocjgOt0vmgl6n
      - GENERIC_AUTH_URL=https://pocket-id.lala.lan/authorize
      - GENERIC_TOKEN_URL=https://pocket-id.lala.lan/api/oidc/token
      - GENERIC_USER_URL=https://pocket-id.lala.lan/api/oidc/userinfo
      - GENERIC_SCOPES=openid email profile groups
      - GENERIC_NAME=Pocket ID
    labels:
      caddy: auth.lala.lan
      caddy.reverse_proxy: "http://auth:3000"

  whoami:
    container_name: whoami
    image: traefik/whoami
    networks:
      - caddysecurity
    environment:
      - COOKIE_SECURE=true
    labels:
      caddy: whoami.lala.lan
      caddy.reverse_proxy: whoami
      caddy.import_0: tinyauth_forwarder *

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    container_name: pocket-id
    restart: unless-stopped
    environment:
      - PUBLIC_APP_URL=https://pocket-id.lala.lan
      - TRUST_PROXY=true
      - MAXMIND_LICENSE_KEY=
      - PUID=1000
      - PGID=1000
      - PORT=3010
    networks:
    - caddysecurity
    volumes:
      - $PWD/data:/app/backend/data
    labels:
      caddy: pocket-id.lala.lan
      caddy.reverse_proxy: pocket-id

networks:
  caddysecurity:

```
