### ISSUE TITLE
[Feature Request] docker labels for whitelist/users

### ISSUE THREAD

**Issue by erwinkramer** [steveiliop56/tinyauth#22]
Introduce label support that make users and whitelists specific for the service you add a label to.

For example: 

- `USERS` might have a label called: `tinyauth.users`
- `OAUTH_WHITELIST` might have a label called: `tinyauth.oauth.whitelist`

Not sure how clever it can be made, maybe another label needs to be introduced to understand the URL of the service, such as `tinyauth.url`

So, you might end up with a service-specific whitelist like this: 

```yaml
dozzle:
  container_name: dozzle
  image: amir20/dozzle:latest
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  labels:
    caddy: ${private_protocol}dozzle.${private_domain}
    caddy.reverse_proxy: "{{upstreams 8080}}"
    caddy.import: tinyauth_forwarder *
    tinyauth.whitelist: foo@gmail.com, bar@gmail.com
    tinyauth.url: ${private_protocol}dozzle.${private_domain}
```
