### ISSUE TITLE
https to http redirection fails after migrating to cloudflare

### ISSUE THREAD

**Issue by erwinkramer** [steveiliop56/tinyauth#25]
Since i moved to cloudflare for DNS resolving i can't seem to get any redirection working from https (tinyauth) to http (backend service). https to https still works fine. All endpoints are backed by cloudflare without proxy settings, just `DNS only` records in cloudflare terms. 

Removing tinyauth makes it just work, so nothing seems to be wrong with my DNS setup. 

As for tinyauth, it shows me the `Insecure Redirect` screen even though i specified `DISABLE_CONTINUE` to `true`, so that's also strange, it didn't do that before. After continuing it just tells me it's logged in, without redirecting. 

Logs:

![Image](https://github.com/user-attachments/assets/f1d2a421-25f4-47b6-81cc-a97937018b7d)

**Comment by steveiliop56** [comment]
Hello,

The insecure thing is normal, I set it this for security reasons. Now for the redirect part it seems really weird, it worked when I tried it with `window.location.href` but maybe this behavior is not the same for all browsers so that's why it's not working on your end. I think the only solution would be to add a manual `<a>` redirect although I will look into this further.

**Comment by erwinkramer** [comment]
> but maybe this behavior is not the same for all browsers so that's why it's not working on your end.

I am on the same browser, nothing else has changed except my DNS provider

**Comment by steveiliop56** [comment]
Does by any chance the console in the browser throw any errors?

**Comment by erwinkramer** [comment]
> Does by any chance the console in the browser throw any errors?

There is nothing logged in the console.

**Comment by steveiliop56** [comment]
Hmm I don't know what could be happening. In my testing environment I have `example.com` and `*.example.com` pointing to traefik so I can test both http and https. I have cloudflare proxy disabled (of course) and everything seems to be working. I will need to investigate this tomorrow with a cup of coffee 😄

**Comment by erwinkramer** [comment]
> Hmm I don't know what could be happening. In my testing environment I have `example.com` and `*.example.com` pointing to traefik so I can test both http and https. I have cloudflare proxy disabled (of course) and everything seems to be working. I will need to investigate this tomorrow with a cup of coffee 😄

Make sure to test with an A-record pointing to a local adres, such as `192.168.1.12`, for the http service.

**Comment by steveiliop56** [comment]
Hmm unfortunately I cannot replicate. I tried setting my DNS to cloudflare's and my redirection still worked. So, when the insecure screen appears and you click continue it redirects to `/`? When the insecure screen appears you should have this in your URL bar:

<img width="383" alt="Image" src="https://github.com/user-attachments/assets/f988bf60-190f-4762-9759-aba1136acd90" />

**Comment by erwinkramer** [comment]
I have this and it does not redirect: 

![Image](https://github.com/user-attachments/assets/edd43fd5-cfa4-4c72-9004-30946ab42902)

**Comment by erwinkramer** [comment]
I think you mean this one, so this one i get first, then it's the logout screen i showed above:

![Image](https://github.com/user-attachments/assets/ebb187e1-9e58-47dc-a90a-8539130bf4ab)

**Comment by steveiliop56** [comment]
Hmm this is really weird indeed, if you open the console on the insecure screen and type `window.location.href = some_http_site` it should redirect. If it doesn't we might have a clue on what's wrong.

**Comment by erwinkramer** [comment]
> Hmm this is really weird indeed, if you open the console on the insecure screen and type `window.location.href = some_http_site` it should redirect. If it doesn't we might have a clue on what's wrong.

Then it just goes to this screen again: 

https://github.com/steveiliop56/tinyauth/issues/25#issuecomment-2627658103

**Comment by steveiliop56** [comment]
When you do that, do the logs say unauthorized or does it return 200 on /api/auth?

**Comment by erwinkramer** [comment]
![Image](https://github.com/user-attachments/assets/5d14fa46-7eb5-4dde-b129-171ea5186824)

**Comment by erwinkramer** [comment]
![Image](https://github.com/user-attachments/assets/082dfa0d-6c7c-4a39-adcc-31e0f30811de)

**Comment by steveiliop56** [comment]
No, I mean tinyauth logs.

**Comment by erwinkramer** [comment]
Sorry, only seeing 200 responses:

![Image](https://github.com/user-attachments/assets/bcf361cd-5139-48fa-9ed5-54a7d1285874)

**Comment by steveiliop56** [comment]
This is so weird. The app seems to do the 307 redirect, it reaches the backend, it verifies it and then you are not getting redirected? This is so weird. Does it only happen with cloudflare DNS?

**Comment by erwinkramer** [comment]
>Does it only happen with cloudflare DNS?

Not sure, only tried 2 and one of them is cloudflare

**Comment by erwinkramer** [comment]
have you tested in private/incognito mode?

**Comment by erwinkramer** [comment]
I don't think it ever worked, since the existing tinyauth cookies might have had a misleading effect. If i change tinyauth to be on http and a backend service on https, it doesn't work either in private/incognito mode. only https to https and http to http works fine

**Comment by steveiliop56** [comment]
I will do more testing tomorrow.

**Comment by steveiliop56** [comment]
Unfortunately I still cannot replicate this issue in any way, I tried with the latest available version of tinyauth on an LXC, with a domain configured like this:

<img width="803" alt="Image" src="https://github.com/user-attachments/assets/ece8629f-7dbb-498f-8f67-bf0f99e225f3" />

*I replaced the IP with the one that the LXC had*

But still no luck, I have tried both with incognito and without in both chrome and edge and the redirection works perfectly. Just in case, I am using this docker compose file:

```yaml
services:
  traefik:
    container_name: traefik
    image: traefik:v3.3
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=postmaster@example.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    container_name: nginx
    image: nginx:latest
    labels:
      traefik.enable: true
      traefik.http.services.nginx.loadbalancer.server.port: 80
      traefik.http.routers.nginx.rule: Host(`nginx.dev.example.com`)
      traefik.http.routers.nginx.middlewares: tinyauth
      traefik.http.middlewares.tinyauth.forwardauth.address: http://tinyauth:3000/api/auth

  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:latest
    environment:
      - SECRET_FILE=BcSSoQlQjsi3MLTd898AxGZG25iQJ83u
      - APP_URL=https://tinyauth.dev.thisdev.gr
      - USERS=user:$$2a$$10$$UdLYoJ5lgPsC0RKqYH/jMua7zIn0g9kPqWmhYayJYLaZQ/FTmH2/u # user:password
      - LOG_LEVEL=0
    labels:
      traefik.enable: true
      traefik.http.services.tinyauth.loadbalancer.server.port: 3000
      traefik.http.routers.tinyauth.rule: Host(`tinyauth.dev.example.com`)
      traefik.http.routers.tinyauth.entrypoints: websecure
      traefik.http.routers.tinyauth.tls.certresolver: myresolver
```

I really don't know what could be wrong with your setup. Tinyauth validates the cookie and returns 200 so your proxy should redirect to the app. Please give this compose file a go to see if the issue is on your proxy config or in tinyauth.
