### ISSUE TITLE
Traefik - Cannot connect to docker-daemon after latest release

### ISSUE THREAD

**Issue by shelldandy** [steveiliop56/tinyauth#29]
After updating im getting this error message trying to access `whoami` with traefik setup:

```
tinyauth  | 2025-02-02T17:51:08Z ERR Failed to check if resource is allowed error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
```

Relevant bits of docker-compose:

```yaml
  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:latest
    environment:
      - SECRET=${TINYAUTH_SECRET}
      - APP_URL=https://${TINYAUTH_URL}
      - USERS=${TINYAUTH_USERS}
      - GENERIC_CLIENT_ID=${GENERIC_CLIENT_ID}
      - GENERIC_CLIENT_SECRET=${GENERIC_CLIENT_SECRET}
      - GENERIC_AUTH_URL=${GENERIC_AUTH_URL}
      - GENERIC_TOKEN_URL=${GENERIC_TOKEN_URL}
      - GENERIC_SCOPES=${GENERIC_SCOPES}
    labels:
      traefik.enable: true
      traefik.http.routers.tinyauth.rule: Host(`${TINYAUTH_URL}`)
      traefik.http.services.tinyauth.loadbalancer.server.port: 3000
      traefik.http.middlewares.tinyauth.forwardauth.address: https://${TINYAUTH_URL}/api/auth
    networks:
      - frontend
      - authentik_network

# in a separate compose file...
  whoami:
    container_name: whoami
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.middlewares=tinyauth"
    networks:
      - frontend
    restart: unless-stopped
```

**Comment by shelldandy** [comment]
I added this to the tinyauth service:

```yaml
   tinyauth:
    # the rest is the same...
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

That stops the docker sock complain (so it might be worth it to add it on the docs)

However with those changes now trying to use generic oauth (with authentik) i get this:

```
tinyauth  | 2025-02-02T18:02:52Z INF Request address=172.18.0.3:46792 latency="61.979µs" method=GET path=/api/oauth/url/generic status=200
tinyauth  | 2025-02-02T18:02:56Z ERR Failed to get user error="Get \"\": unsupported protocol scheme \"\""
```
