### ISSUE TITLE
Traefik does not respect X-Forwarded-Host when using docker host mode

### ISSUE THREAD

**Issue by liveder** [steveiliop56/tinyauth#35]
When using network_mode: host in docker, the redirect_uri always resolves to APP_URL.
The reason is that Traefik does not respect the X-Forwarded-Host header from NATed IP addresses, such as the internal Docker IP pool (172.16.0.0/12).

This issue can be resolved by adding trustedIPs in traefik.yaml:

```
entryPoints:
  https:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "172.16.0.0/12"
```
