### ISSUE TITLE
[BUG] Error messages on docker + nginx proxy manager

### ISSUE THREAD

**Issue by javierspn** [steveiliop56/tinyauth#41]
First and foremost, thanks! Nice tiny piece of software.

**Describe the bug**
Many errors on the container log such as these ones (see INF and WRN before the actual error):

```cfg
2025-02-27T08:41:27Z ERR Request address=172.19.0.2:43012 latency="270.923µs" method=GET path=/api/auth/nginx status=401
2025-02-27T08:41:27Z INF Request address=172.19.0.2:43024 latency="139.668µs" method=GET path=/ status=200
2025-02-27T08:41:27Z INF Request address=172.19.0.2:43032 latency=1.414164ms method=GET path=/assets/index-023Kh3A3.js status=200
2025-02-27T08:41:27Z INF Request address=172.19.0.2:43044 latency=1.213083ms method=GET path=/assets/index-Dcj4c2oZ.css status=200
2025-02-27T08:41:35Z WRN Session cookie invalid
2025-02-27T08:41:35Z INF Request address=172.19.0.2:50562 latency="117.137µs" method=GET path=/favicon-32x32.png status=200
2025-02-27T08:41:35Z INF Request address=172.19.0.2:50556 latency="243.49µs" method=GET path=/api/status status=200
2025-02-27T08:41:45Z INF Request address=172.19.0.2:33036 latency=128.91869ms method=POST path=/api/login status=200
2025-02-27T08:41:45Z INF Request address=172.19.0.2:33046 latency="83.161µs" method=GET path=/ status=200
2025-02-27T08:41:45Z INF Request address=172.19.0.2:33060 latency="280.938µs" method=GET path=/assets/index-Dcj4c2oZ.css status=200
2025-02-27T08:41:45Z INF Request address=172.19.0.2:33052 latency="848.618µs" method=GET path=/assets/index-023Kh3A3.js status=200
2025-02-27T08:41:46Z WRN Session cookie invalid
2025-02-27T08:41:46Z ERR Request address=172.19.0.2:33070 latency="321.335µs" method=GET path=/api/auth/nginx status=401
2025-02-27T08:41:47Z WRN Session cookie invalid
2025-02-27T08:41:47Z ERR Request address=172.19.0.2:33084 latency="230.369µs" method=GET path=/api/auth/nginx status=401
2025-02-27T08:41:51Z INF Request address=172.19.0.2:33100 latency="135.354µs" method=GET path=/favicon-32x32.png status=200
```

**To Reproduce**
1. It just happens every time. See docker logs with `sudo docker container logs tinyauth`

**Expected behavior**
No errors shall be displayed?

**Screenshots**
Current configuration:

docker compose file:

```yaml
services:

  tinyauth:

    container_name: "${CONTAINER_NAME}"
    image: ${CONTAINER_IMAGE}

    environment:
      TZ: ${TZ}
      SECRET: ${SECRET}
      APP_URL: ${APP_URL}
      USERS: ${USERS}

    networks:
      - proxied

    restart: ${POLICY_RESTART}

    logging:

      driver: ${LOG_TYPE}
      options:
        max-size: ${LOG_SIZE}
        max-file: ${LOG_FILES}

networks:
  proxied:
    name: proxied

```
.env file (SECRET and USERS modified for obvious privacy reasons)

```cfg
CONTAINER_NAME=tinyauth
CONTAINER_IMAGE=ghcr.io/steveiliop56/tinyauth:latest
TZ=Europe/Madrid
SECRET=SuperLongSecretStringThisIsYeah.
APP_URL=https://auth.example.com
USERS=megauser:$2y$10$mzyBg6KS.udbeHIcvxrKzOI.hXS6MBvh8mZr5v53jWxewnyKu2jO6
POLICY_RESTART=unless-stopped
LOG_TYPE=json-file
LOG_SIZE=10M
LOG_FILES=3
```
**Logs**
Please include the Tinyauth logs below, make sure to not include sensitive info.

**Device (please complete the following information):**
 - OS: Debian 12
 - Browser: Tested on FF, Safari, Chrome, Edge
 - Tinyauth: latest, v3.0.1
 - Docker:
```bash
 Client: Docker Engine - Community
 Version:           27.5.1
 API version:       1.47
 Go version:        go1.22.11
 Git commit:        9f9e405
 Built:             Wed Jan 22 13:41:17 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.5.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.11
  Git commit:       4c9b3b0
  Built:            Wed Jan 22 13:41:17 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**
**Additional context**

**Comment by steveiliop56** [comment]
Are you able to login? Is the logging the issue? You may see warning and errors because the logger determines what level it should use based on the error code e.g. 200-300 is info, 300-400 warning etc. So when it returns 401 to nginx proxy manager it's really not error, it just tells it that it's unauthorized.

**Comment by javierspn** [comment]
Yes. I am able to login.
But weirdly, when I came home the proxing part has stopped working at all. It times out, when it was perfectly working from another network (work).

I am perfectly able to login when I point directly to https://auth.example.com in my browser:

![Image](https://github.com/user-attachments/assets/16dd51af-d406-43a8-946c-63dabd26f2b8)

But when I use any of the proxied services it times out.

EDIT: And now it works again..this is weird, I will keep this open for a while to see if it is stable.

Thanks!

**Comment by steveiliop56** [comment]
Can you please share your proxy setup? What exactly stops working? You go to myapp.example.com and it doesn't redirect you at all to tinyauth or it redirects you to tinyauth but tinyauth doesn't redirect you back?

**Comment by javierspn** [comment]
Sure!.

docker compose:
```yaml
services:


  npm:

    container_name: "${CONTAINER_NAME}"
    image: ${CONTAINER_IMAGE}

    environment:
      TZ: ${TZ}

    networks:
      - proxied

    ports:
      - ${NPM_HTTP_PORT}
      - ${NPM_HTTPS_PORT}
      - ${NPM_ADMIN_PORT}

    restart: ${POLICY_RESTART}

    volumes:
      - ${NPM_VOLUME}
      - ${NPM_LETSENCRYPT_VOLUME}

    logging:

      driver: ${LOG_TYPE}
      options:
        max-size: ${LOG_SIZE}
        max-file: ${LOG_FILES}

networks:
  proxied:
    name: proxied
```

.env file:

```config
CONTAINER_NAME=npm
CONTAINER_IMAGE=jc21/nginx-proxy-manager:latest
TZ=Europe/Madrid
POLICY_RESTART=unless-stopped
NPM_HTTP_PORT=80:80
NPM_HTTPS_PORT=443:443
NPM_ADMIN_PORT=81:81
NPM_VOLUME=/docker/data/npm:/data
NPM_LETSENCRYPT_VOLUME=/docker/data/npm/letsencrypt:/etc/letsencrypt
LOG_TYPE=json-file
LOG_SIZE=10M
```

![Image](https://github.com/user-attachments/assets/1e007357-b7cf-4e03-9b97-2a77f366a772)

![Image](https://github.com/user-attachments/assets/5d85edf4-a6ba-4d7e-9332-ba864fb9fff8)

And the advanced configuration on the site:

```config
auth_request /tinyauth;
error_page 401 = @tinyauth_login;

location /tinyauth {
  proxy_pass http://tinyauth:3000/api/auth/nginx;
  proxy_set_header x-forwarded-proto $scheme;
  proxy_set_header x-forwarded-host $http_host;
  proxy_set_header x-forwarded-uri $request_uri;
}

location @tinyauth_login {
  return 302 http://auth.example.com/login?redirect_uri=$scheme://$http_host$request_uri; # make sure to replace the http://tinyauth.example.com with your own app URL
}
```
