### ISSUE TITLE
SSL_ERROR_INTERNAL_ERROR_ALERT

### ISSUE THREAD

**Issue by lockheed** [steveiliop56/tinyauth#57]
I followed all the steps on setting this up with caddy-docker-proxy, but  when I go to the address of the service in any browser, I am getting this:

> Secure Connection Failed
> 
> An error occurred during a connection to ladder.domain.one. Peer reports it experienced an internal error.
> 
> Error code: SSL_ERROR_INTERNAL_ERROR_ALERT
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the web site owners to inform them of this problem.

**Comment by steveiliop56** [comment]
Hello!

A bit hard to debug this without any info from your setup. Can you please follow the bug issue template which is available [here](https://github.com/steveiliop56/tinyauth/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)? Github would have automatically shown this to you if you created a bug report.

**Comment by lockheed** [comment]
I don't think that format would add any new information, so here's my compose files:

1. I added this to caddy service in the compose file:

```
    labels:
      caddy: (tinyauth_forwarder)
      caddy.forward_auth: tinyauth:3000
      caddy.forward_auth.uri: /api/auth/caddy
```
2. I added separate service to caddy compose file:
```
  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:v3
    restart: unless-stopped
    environment:
      - APP_URL=http://tinyauth.mydomain.com
      - SECRET=some-random-32-chars-string
      - USERS=user:$2a$10$YnveSykW.EASfa3f4NrxeBz7KtNBxCeaqGCGeXkzxEy9X4bGIbiW
      - GOOGLE_CLIENT_ID=11111111111-uadfcdafs15r25fbolp1a7m9dhq.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=SFSASAFA-kQRT#F#SSAP2_6F_aAsfSFsh-Q_PEL
      - OAUTH_WHITELIST=myemail@aol.com
    labels:
      caddy: http://tinyauth.mydomain.com
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - proxy      
```
3, I added relevant line to labels in the compose file of the service (ladder, in that case):
```
    labels:
        caddy: ladder.domain.one
        caddy.reverse_proxy: "* {{upstreams 8080}}"  
        com.centurylinklabs.watchtower.enable: true
        caddy.import: tinyauth_forwarder *
```

4. Went to the service www address and was greeted by the above error.

I am running Arch, so everything is in the latest version.
