### ISSUE TITLE
[BUG] Google  OAuth not recognized when using `GOOGLE_CLIENT_SECRET_FILE`

### ISSUE THREAD

**Issue by Ginden** [steveiliop56/tinyauth#69]
**Describe the bug**

When using `GOOGLE_CLIENT_SECRET_FILE` env variable, OAuth is not configured.

**To Reproduce**

Following docker-compose works:

```
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3
    container_name: tinyauth
    restart: unless-stopped
    environment:
      APP_URL: "https://tinyauth.example.com"
      SECRET_FILE: "/config/secret"
      OAUTH_WHITELIST_FILE: "/config/oauth_whitelist"
      GOOGLE_CLIENT_ID: "454....googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "G...Q"
      # GOOGLE_CLIENT_SECRET_FILE: "/config/google_client_secret"
```

This results in `FTL No users or OAuth configured error="no users or OAuth configured"` error:

```
services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3
    container_name: tinyauth
    restart: unless-stopped
    environment:
      APP_URL: "https://tinyauth.example.com"
      SECRET_FILE: "/config/secret"
      OAUTH_WHITELIST_FILE: "/config/oauth_whitelist"
      GOOGLE_CLIENT_ID: "454....googleusercontent.com"
      GOOGLE_CLIENT_SECRET_FILE: "/config/google_client_secret"
```

**Expected behavior**

Version with `_FILE` works properly

**Logs**

```
tinyauth  | 2025-04-09T21:36:03Z INF Starting tinyauth version=v3.2.0
tinyauth  | 2025-04-09T21:36:03Z INF Parsing users
tinyauth  | 2025-04-09T21:36:03Z FTL No users or OAuth configured error="no users or OAuth configured"
tinyauth exited with code 1
```

**Device (please complete the following information):**
 - OS: Ubuntu 24
 - Browser N/A
 - Tinyauth 3.2.0
 - Docker 27.5.1

**
**Additional context**

`/config` is mounted correctly.

```
docker compose exec tinyauth ls /config
google_client_id      google_client_secret  oauth_whitelist       secret                users
```
